#!/usr/bin/env bash
# Install global terminal shortcuts for op-xai into ~/.local/bin
#
#   op-xai …              primary
#   opencode-multi-xai …  alias
#   xai-multi …           alias
#
# Usage:
#   bash scripts/install-cli.sh
#   bash scripts/install-cli.sh --path   # also ensure PATH in shell rc
#   npm run install-cli
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLI="$ROOT/scripts/cli.ts"
BIN_DIR="${MULTI_XAI_BIN_DIR:-$HOME/.local/bin}"
FIX_PATH=0

for arg in "$@"; do
  case "$arg" in
    --path|--fix-path) FIX_PATH=1 ;;
    -h|--help)
      echo "Usage: bash scripts/install-cli.sh [--path]"
      echo "  --path  Append ~/.local/bin to ~/.zshrc and/or ~/.bashrc if missing"
      exit 0
      ;;
  esac
done

resolve_runner() {
  if command -v bun >/dev/null 2>&1; then
    command -v bun
    return 0
  fi
  # Prefer absolute common bun path
  if [[ -x "$HOME/.bun/bin/bun" ]]; then
    echo "$HOME/.bun/bin/bun"
    return 0
  fi
  return 1
}

BUN_BIN="$(resolve_runner || true)"
if [[ -z "${BUN_BIN:-}" ]]; then
  echo "error: bun not found on PATH" >&2
  echo "Install bun: https://bun.sh  (required to run scripts/cli.ts)" >&2
  exit 1
fi

if [[ ! -f "$CLI" ]]; then
  echo "error: missing $CLI" >&2
  exit 1
fi

# Ensure deps exist (OpenTUI etc.) so global CLI works from any cwd
if [[ ! -d "$ROOT/node_modules" ]]; then
  echo "note: node_modules missing — run npm install / bun install in $ROOT first" >&2
fi

mkdir -p "$BIN_DIR"

write_shim() {
  local name="$1"
  local target="$BIN_DIR/$name"
  cat >"$target" <<EOF
#!/usr/bin/env bash
# opencode-multi-xai global CLI shim — generated by scripts/install-cli.sh
# Repo: $ROOT
set -euo pipefail
ROOT="$ROOT"
CLI="\$ROOT/scripts/cli.ts"
BUN="$BUN_BIN"
if [[ ! -f "\$CLI" ]]; then
  echo "error: CLI source missing: \$CLI" >&2
  echo "Re-run install from the opencode-multi-xai repo." >&2
  exit 1
fi
if [[ ! -x "\$BUN" ]] && ! command -v bun >/dev/null 2>&1; then
  echo "error: bun not found (was: \$BUN)" >&2
  exit 1
fi
if [[ ! -x "\$BUN" ]]; then
  BUN="\$(command -v bun)"
fi
# Always run with repo as cwd so relative imports / package resolve work
cd "\$ROOT"
exec "\$BUN" "\$CLI" "\$@"
EOF
  chmod +x "$target"
}

write_shim "op-xai"
write_shim "opencode-multi-xai"
write_shim "xai-multi"

# Remove legacy one-shot wrappers (xai-list, xai-add, ...) if present
LEGACY=(
  status list add limits quota health switch remove
  enable disable label tag note refresh flag unflag prune help priority
)
for cmd in "${LEGACY[@]}"; do
  rm -f "$BIN_DIR/xai-$cmd"
done

ensure_path_rc() {
  local rc="$1"
  local line='export PATH="$HOME/.local/bin:$PATH"'
  [[ -f "$rc" ]] || touch "$rc"
  if grep -qF '.local/bin' "$rc" 2>/dev/null; then
    echo "  PATH already referenced in $rc"
    return 0
  fi
  {
    echo ""
    echo "# opencode-multi-xai / op-xai global CLI"
    echo "$line"
  } >>"$rc"
  echo "  appended PATH to $rc"
}

echo "Installed global CLI into $BIN_DIR"
echo "  op-xai"
echo "  opencode-multi-xai"
echo "  xai-multi"
echo "  → $BUN_BIN $CLI"
echo ""

PATH_OK=0
if echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
  PATH_OK=1
fi

if [[ "$FIX_PATH" -eq 1 ]]; then
  echo "Ensuring $BIN_DIR is on PATH in shell rc…"
  # Prefer the user's current shell
  case "${SHELL:-}" in
    */zsh) ensure_path_rc "$HOME/.zshrc" ;;
    */bash) ensure_path_rc "$HOME/.bashrc" ;;
    *)
      [[ -f "$HOME/.zshrc" ]] && ensure_path_rc "$HOME/.zshrc"
      [[ -f "$HOME/.bashrc" ]] && ensure_path_rc "$HOME/.bashrc"
      if [[ ! -f "$HOME/.zshrc" && ! -f "$HOME/.bashrc" ]]; then
        ensure_path_rc "$HOME/.profile"
      fi
      ;;
  esac
  export PATH="$BIN_DIR:$PATH"
  PATH_OK=1
  echo ""
fi

echo "Try (global, any directory):"
echo "  op-xai tui"
echo "  op-xai help"
echo "  op-xai list"
echo "  op-xai status"
echo "  op-xai limits --probe"
echo "  op-xai health"
echo "  op-xai add"
echo ""

if [[ "$PATH_OK" -eq 0 ]]; then
  echo "NOTE: $BIN_DIR is not on PATH in this shell."
  echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo "Or permanently:"
  echo "  bash scripts/install-cli.sh --path"
  echo "  # then: source ~/.zshrc   (or open a new terminal)"
elif ! command -v op-xai >/dev/null 2>&1; then
  # PATH has bin dir but hash not refreshed
  export PATH="$BIN_DIR:$PATH"
  hash -r 2>/dev/null || true
fi

if command -v op-xai >/dev/null 2>&1; then
  echo "Verified: $(command -v op-xai)"
  op-xai help 2>/dev/null | head -3 || true
fi
